version: "3.8"

services:
  backend:
    build:
      context: ./iot
      dockerfile: Dockerfile
    container_name: iot-backend
    ports:
      - "4000:4000"
    networks:
      - iot-network

  frontend:
    build:
      context: ./iot_front
      dockerfile: Dockerfile
    container_name: iot-frontend
    ports:
      - "4001:4001" 
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://143.110.238.208:4000/api

    networks:
      - iot-network

networks:
  iot-network:
    driver: bridge
