version: "3.8"

services:
  backend:
    build:
      context: ./iot
      dockerfile: Dockerfile
    container_name: iot-backend
    ports:
      - "4000:3000"
    networks:
      - iot-network

  frontend:
    build:
      context: ./iot-client
      dockerfile: Dockerfile
    container_name: iot-frontend
    ports:
      - "4001:3000"  # Next.js sirve en 3000, lo exponemos como 3001
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://iot-backend:4000
    networks:
      - iot-network

networks:
  iot-network:
    driver: bridge
